
#
# This is based on our existing Splunk Lab
#
FROM splunk-lab-core

#
# Install Python for Scientific computing and Splunk ML Toolkit
#
RUN wget https://s3.amazonaws.com/dmuth-splunk-lab/python-for-scientific-computing-for-linux-64-bit_14.tgz \
	&& tar xfvz python-for-scientific-computing-for-linux-64-bit_14.tgz \
	&& mv Splunk_SA_Scientific_Python_linux_x86_64 /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/python-for-scientific-computing-for-linux-64-bit_14.tgz \

	&& wget https://s3.amazonaws.com/dmuth-splunk-lab/splunk-machine-learning-toolkit_420.tgz \
	&& tar xfvz splunk-machine-learning-toolkit_420.tgz \
	&& mv Splunk_ML_Toolkit /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/splunk-machine-learning-toolkit_420.tgz 


#####
#
# Now that apps are installed, we can install the config files, with a lot less 
# stuff being downlaoded/images being re-built.
#


#
# Copy in vendor/README.md, which contains license info on the various apps.
#
COPY vendor/README.md /README.md


#
# Copy in some Splunk configuration
#
COPY splunk-config/splunk-launch.conf /opt/splunk/etc/
COPY splunk-config/* /opt/splunk/etc/system/local/


#
# Install the Splunk Lab app and set it to the default
#
WORKDIR /tmp
COPY splunk-lab-app /opt/splunk/etc/apps/splunk-lab
RUN mkdir -p /opt/splunk/etc/users/admin/user-prefs/local \
	&& mv /opt/splunk/etc/apps/splunk-lab/user-prefs.conf /opt/splunk/etc/users/admin/user-prefs/local/


#
# Expose Splunk web
#
EXPOSE 8000/tcp

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]



