
#
# This is based on our existing Splunk Lab
#
FROM splunk-lab

#
# Install Python for Scientific computing and Splunk ML Toolkit
#
RUN wget https://s3.amazonaws.com/dmuth-splunk-lab/python-for-scientific-computing-for-linux-64-bit_14.tgz
RUN tar xfvz python-for-scientific-computing-for-linux-64-bit_14.tgz
RUN mv Splunk_SA_Scientific_Python_linux_x86_64 /opt/splunk/etc/apps/
RUN rm -fv /tmp/python-for-scientific-computing-for-linux-64-bit_14.tgz

RUN wget https://s3.amazonaws.com/dmuth-splunk-lab/splunk-machine-learning-toolkit_420.tgz
RUN tar xfvz splunk-machine-learning-toolkit_420.tgz 
RUN mv Splunk_ML_Toolkit /opt/splunk/etc/apps/
RUN rm -fv /tmp/splunk-machine-learning-toolkit_420.tgz 


#
# Expose Splunk web
#
EXPOSE 8000/tcp

ENTRYPOINT ["/entrypoint.sh"]



