
#
# Build splunk-lab-core, which is used as a base for splunk-lab and splunk-lab-ml
#
# The reason for this architecture is so that changes to things like config files
# can be done AFTER the apps in each image are installed, so I don't have to keep
# reinstalling the apps when I'm just tweaking a config file.
#
# Based on https://github.com/splunk/docker-splunk/blob/master/enterprise/Dockerfile
#
# I slimmed this down, as I have no desire to run as a separate user, set up a Deployment
# Server, generate PDFs, etc.  All I want to do is run a this single app.
#
FROM debian:stretch

ENV SPLUNK_PRODUCT splunk
ENV SPLUNK_VERSION 8.0.1
ENV SPLUNK_BUILD 6db836e2fb9e
ENV SPLUNK_FILENAME splunk-${SPLUNK_VERSION}-${SPLUNK_BUILD}-Linux-x86_64.tgz

ENV SPLUNK_HOME /opt/splunk

ARG DEBIAN_FRONTEND=noninteractive

#
# make the "en_US.UTF-8" locale so splunk will be utf-8 enabled by default
#
RUN apt-get update \
	&& apt-get install -y --no-install-recommends apt-utils \
	&& apt-get install -y locales \
	&& rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8 

#
# Download official Splunk release, verify checksum and unzip in /opt/splunk
# Also backup etc folder, so it will be later copied to the linked volume
#
RUN apt-get update && apt-get install -y wget procps fping less iptables \
    && mkdir -p ${SPLUNK_HOME} \
    && wget -qO /tmp/${SPLUNK_FILENAME} https://download.splunk.com/products/${SPLUNK_PRODUCT}/releases/${SPLUNK_VERSION}/linux/${SPLUNK_FILENAME} \
    && wget -qO /tmp/${SPLUNK_FILENAME}.md5 https://download.splunk.com/products/${SPLUNK_PRODUCT}/releases/${SPLUNK_VERSION}/linux/${SPLUNK_FILENAME}.md5 \
    && (cd /tmp && md5sum -c ${SPLUNK_FILENAME}.md5) \
    && tar xzf /tmp/${SPLUNK_FILENAME} --strip 1 -C ${SPLUNK_HOME} \
    && rm /tmp/${SPLUNK_FILENAME} \
    && rm /tmp/${SPLUNK_FILENAME}.md5 


#
# Link to our data directory and search app.
# 
# The /data/ directory is used in a volume mount but /app/ is not.
# The reason I still have it is because it will be helpful for
# anything who may be exploring the container. 
#
# (Yes, that means *you*, Chris in Seattle)
#
RUN ln -s /opt/splunk/var/lib/splunk/ /data \
	&& ln -s /opt/splunk/etc/apps/splunk-lab/local /app 

WORKDIR /tmp

COPY splunk-packages-from-s3/* /tmp/splunk-packages/

#
# Install Syndication app
# https://splunkbase.splunk.com/app/2646/
#
RUN	\
	tar xfvz /tmp/splunk-packages/syndication-input-rssatomrdf_12.tgz \
	&& mv syndication /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/splunk-packages/syndication-input-rssatomrdf_12.tgz \
#
# Install Rest API Modular Input
# https://splunkbase.splunk.com/app/1546/#/details
#
	&& tar xfvz /tmp/splunk-packages/rest-api-modular-input_154.tgz \
	&& mv rest_ta /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/splunk-packages/rest-api-modular-input_154.tgz \
#
# Install Wordcloud app
# https://splunkbase.splunk.com/app/3212/
#
	&& tar xfvz /tmp/splunk-packages/wordcloud-custom-visualization_111.tgz \
	&& mv wordcloud_app /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/splunk-packages/wordcloud-custom-visualization_111.tgz \
#
# Install Slack Notification Alert
# https://splunkbase.splunk.com/app/2878/
#
	&& tar xfvz /tmp/splunk-packages/slack-notification-alert_203.tgz \
	&& mv slack_alerts /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/splunk-packages/slack-notification-alert_203.tgz \
#
# Install Splunk Dashboard Examples
# https://splunkbase.splunk.com/app/1603/
#
	&& tar xfvz /tmp/splunk-packages/splunk-dashboard-examples_800.tgz \
	&& mv simple_xml_examples /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/splunk-packages/splunk-dashboard-examples_800.tgz \
#
# Install Eventgen
# https://splunkbase.splunk.com/app/1924
#
	&& tar xfvz /tmp/splunk-packages/eventgen_653.tgz \
	&& mv SA-Eventgen /opt/splunk/etc/apps/ \
	&& rm -fv /tmp/splunk-packages/eventgen_653.tgz



